[project]
name = "webinar-vibe-coding-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.2",
    "sqlalchemy>=2.0.45",
]
